SECRET_KEY = "SERECT-KEY-IS-SECRET"
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:@localhost/doan"
SQLALCHEMY_TRACK_MODIFICATIONS = True
MAIL_SERVER = 'smp.googlemail.com'
MAIL_USERNAME = "shinichi24567@gmail.com"
MAIL_PASSWORD = "123456789"  # đặt lại password cho hợp lý
UPLOAD_FOLDER = 'C:/Users/DELL/Desktop/workspace/python-projects/LibraryManagement/python-flask/library/static/uploads'
MAX_CONTENT_LENGTH = 16 * 1024 * 1024
ALLOWED_EXTENSIONS = ["png", "jpg", "jpeg", "gif"]